version: '3'
services:
  app:
    container_name: bookhub_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000 
    environment:
      - PORT=${PORT}
      - APP_PRIVATE_KEY=${APP_PRIVATE_KEY}
      - DB_DRIVER=${DB_DRIVER}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - PGADMIN_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_PASSWORD=${PGADMIN_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: on-failure
    volumes:
      - app:/usr/src/app/
    depends_on:
      - db
      - pgadmin
      - redis
    networks:
      - network_service
    expose:
      - 8000
  
  db: 
    image: postgres:14
    container_name: bookhub_db
    hostname: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - psql:/var/lib/postgresql/data
    networks:
      - network_service
    expose:
      - 5432

  pgadmin:
    image: dpage/pgadmin4:7.1
    container_name: bookhub_pgadmin
    ports:
      - "5050:5050"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
      - PGADMIN_LISTEN_PORT=${PGADMIN_PORT}
    volumes:
        - pgadmin:/var/lib/pgadmin
    depends_on:
        - db
    networks:
      - network_service
    expose:
      - 5050
    restart: unless-stopped

  redis:
    image: bitnami/redis
    container_name: bookhub_redis
    hostname: redis
    ports:
      - 6379:6379
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
        - db
        - pgadmin
    networks:
      - network_service
    expose:
      - 6379

volumes:
  app:
  psql:
  pgadmin:


networks:
  network_service:
    driver: bridge